---
title: "FirstR"
output: html_document
date: "2023-06-21"
---

```{r P-Simulation}

test <- generating_parent(chromosome_length = 10) 
View(test)


```

```{r F1-Simulation-Mouse-A}

## Simulating mouse "a" from the F1 cross

## Which parent 1 chromosome mouse "a" got
# x <- sample(x = c(1, 2), size = 1)
# 
# parent1_chrom <- parent1[,x]
# 
# ## Which parent 2 chromosome mouse "a" got, taking a random sample from 1 or 2 to decide like previous
# x <- sample(x = c(1, 2), size = 1)
# ## Pulling the chromosome from our parent generation like previous
# ## [,] subsets from a dataframe
# parent2_chrom <- parent2[,x]

## choosing recombination locations from 100-loci chromosome
recomb_loci <- sort(sample( 1:100, size = 3, replace = FALSE))

## Recombining loci by alternating b/w the parent's chromosome at the recombination loci
F1_a_CH1 <- c(parent1_chrom[1:recomb_loci[1]],parent2_chrom[(recomb_loci[1]+1):recomb_loci[2]],parent1_chrom[(recomb_loci[2]+1):recomb_loci[3]], parent2_chrom[(recomb_loci[3]+1):100])

## Creating mouse "a"'s second chromosome by "reversing" the first
F1_a_CH2 <- as.numeric(!F1_a_CH1)

## Save as dataframe so it is easier
F1_a <- data.frame(CH1 = F1_a_CH1, CH2 = F1_a_CH2)
```

```{r F1-Simulation-Mouse-B}
## Simulating mouse "b" from the F1 cross

## Which parent 1 chromosome mouse "b" got
x <- sample(x = c(1, 2), size = 1)

parent1_chrom <- parent1[,x]

## Which parent 2 chromosome mouse "b" got, taking a random sample from 1 or 2 to decide like previous
x <- sample(x = c(1, 2), size = 1)
## Pulling the chromosome from our parent generation like previous
## [,] subsets from a dataframe
parent2_chrom <- parent2[,x]

## choosing recombination locations from 100-loci chromosome
recomb_loci <- sort(sample( 1:100, size = 3, replace = FALSE))

## Recombining loci by alternating b/w the parent's chromosome at the recombination loci
F1_b_CH1 <- c(parent1_chrom[1:recomb_loci[1]],parent2_chrom[(recomb_loci[1]+1):recomb_loci[2]],parent1_chrom[(recomb_loci[2]+1):recomb_loci[3]], parent2_chrom[(recomb_loci[3]+1):100])

## Creating mouse "b"'s second chromosome by "reversing" the first
F1_b_CH2 <- as.numeric(!F1_b_CH1)

## Save as dataframe so it is easier
F1_b <- data.frame(CH1 = F1_b_CH1, CH2 = F1_b_CH2)
```

```{r F2-Simulating-Mouse-A}

x <- sample(x = c(1, 2), size = 1)

F1_a_chrom <- F1_a[,x]

x <- sample(x = c(1, 2), size = 1)

F1_b_chrom <- F1_b[,x]

recomb_loci <- sort(sample( 1:100, size = 3, replace = FALSE))

F2_a_CH1 <- c(F1_a_chrom[1:recomb_loci[1]],F1_b_chrom[(recomb_loci[1]+1):recomb_loci[2]],F1_a_chrom[(recomb_loci[2]+1):recomb_loci[3]], F1_b_chrom[(recomb_loci[3]+1):100])

F2_a_CH2 <- c(F1_b_chrom[1:recomb_loci[1]],F1_a_chrom[(recomb_loci[1]+1):recomb_loci[2]],F1_b_chrom[(recomb_loci[2]+1):recomb_loci[3]], F1_a_chrom[(recomb_loci[3]+1):100])

F2_a <- data.frame(CH1 = F2_a_CH1, CH2 = F2_a_CH2)
```

```{r}

## Adding a column to your data for the color of the dots

# 0 = "red4"

# 1 = "skyblue3"

F2_a$CH1_color <- NA
F2_a$CH2_color <- NA

## This for loop is stepping through every number from 1 to 100
for(i in 1:100) {
  if(F2_a[i, "CH1"]== 0){
    F2_a[i, "CH1_color"] <- "red4"
  }
}

for(i in 1:100) {
  if(F2_a[i, "CH2"]== 0){
    F2_a[i, "CH2_color"] <- "red4"
  }
}

##Instead of repeating the above
F2_a <- F2_a %>% replace(is.na(.), "skyblue3")


plot(x = rep(1, 100), y = 1:100, col = F2_a$CH1_color, xlim= c(.9,2.1))
points(x = rep(2,100), y=1:100, col = F2_a$CH2_color)

```
